// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mysqltest.Models;

namespace mysqltest.Migrations
{
    [DbContext(typeof(ClubsContext))]
    [Migration("20210902125549_mysqltest.models.initStudents")]
    partial class mysqltestmodelsinitStudents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("mysqltest.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 697, DateTimeKind.Local).AddTicks(2579),
                            Name = "International",
                            Type = "Other",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 700, DateTimeKind.Local).AddTicks(7979)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 700, DateTimeKind.Local).AddTicks(8606),
                            Name = "Math",
                            Type = "Academic",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 700, DateTimeKind.Local).AddTicks(8638)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 700, DateTimeKind.Local).AddTicks(8652),
                            Name = "Diving",
                            Type = "Sport",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 700, DateTimeKind.Local).AddTicks(8655)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 700, DateTimeKind.Local).AddTicks(8660),
                            Name = "Strollers",
                            Type = "Leisure",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 700, DateTimeKind.Local).AddTicks(8664)
                        });
                });

            modelBuilder.Entity("mysqltest.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1999, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7283),
                            FirstName = "Ali",
                            LastName = "Tayari",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7359)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1963, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7447),
                            FirstName = "Dmitry",
                            LastName = "Apraksin",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7452)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2004, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7459),
                            FirstName = "Ivan",
                            LastName = "Ivanou",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7462)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7467),
                            FirstName = "Petr",
                            LastName = "Petrov",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7473)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1989, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7479),
                            FirstName = "Sidor",
                            LastName = "Sidorov",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7484)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2000, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7491),
                            FirstName = "Pambos",
                            LastName = "Boss",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7496)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1998, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7502),
                            FirstName = "Christos",
                            LastName = "Christou",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7507)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1999, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7513),
                            FirstName = "Savvas",
                            LastName = "Savvou",
                            UpdatedDate = new DateTime(2021, 9, 2, 15, 55, 48, 702, DateTimeKind.Local).AddTicks(7518)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
